// AUTO-GENERATED by scripts/sync-formats.js — DO NOT EDIT
// Source of truth: formats.json

/**
 * Definition of a supported file format
 */
export interface FormatDefinition {
  /** Internal file type identifier, also used as settings key (e.g., 'mermaid', 'vega-lite') */
  fileType: string;
  /** File extensions without dot (e.g., ['mermaid', 'mmd']) */
  extensions: string[];
  /** VS Code language ID (e.g., 'mermaid', 'graphviz') */
  languageId: string;
}

/**
 * All supported non-markdown formats.
 * Markdown (.md, .markdown) is always supported and not listed here.
 */
export const SUPPORTED_FORMATS: readonly FormatDefinition[] = [
  {
    "fileType": "slidev",
    "extensions": [
      "slides.md"
    ],
    "languageId": "markdown"
  },
  {
    "fileType": "mermaid",
    "extensions": [
      "mermaid",
      "mmd"
    ],
    "languageId": "mermaid"
  },
  {
    "fileType": "plantuml",
    "extensions": [
      "plantuml",
      "puml"
    ],
    "languageId": "plantuml"
  },
  {
    "fileType": "vega",
    "extensions": [
      "vega"
    ],
    "languageId": "vega"
  },
  {
    "fileType": "vega-lite",
    "extensions": [
      "vl",
      "vega-lite"
    ],
    "languageId": "vega"
  },
  {
    "fileType": "dot",
    "extensions": [
      "gv",
      "dot"
    ],
    "languageId": "graphviz"
  },
  {
    "fileType": "infographic",
    "extensions": [
      "infographic"
    ],
    "languageId": "infographic"
  },
  {
    "fileType": "canvas",
    "extensions": [
      "canvas"
    ],
    "languageId": "canvas"
  },
  {
    "fileType": "drawio",
    "extensions": [
      "drawio"
    ],
    "languageId": "drawio"
  }
];

// =============================================================================
// Derived lookup tables (built once from SUPPORTED_FORMATS)
// =============================================================================

/** Map file extension (without dot) → fileType. Includes 'md'/'markdown' → 'markdown'. */
export const EXTENSION_TO_FILE_TYPE: Record<string, string> = { md: 'markdown', markdown: 'markdown' };
for (const f of SUPPORTED_FORMATS) {
  for (const ext of f.extensions) {
    EXTENSION_TO_FILE_TYPE[ext] = f.fileType;
  }
}

/** Map dotted extension (e.g. '.mermaid') → fileType */
export const DOT_EXTENSION_TO_FILE_TYPE: Record<string, string> = {};
for (const f of SUPPORTED_FORMATS) {
  for (const ext of f.extensions) {
    DOT_EXTENSION_TO_FILE_TYPE[`.${ext}`] = f.fileType;
  }
}

/** All supported extensions with dot, including markdown */
export const ALL_SUPPORTED_EXTENSIONS: readonly string[] = [
  '.md', '.markdown',
  ...SUPPORTED_FORMATS.flatMap(f => f.extensions.map(e => `.${e}`)),
].sort((a, b) => b.length - a.length);

/** All supported extensions without dot, excluding markdown */
export const ALL_FORMAT_EXTENSIONS: readonly string[] =
  SUPPORTED_FORMATS.flatMap(f => f.extensions);

/** Unique VS Code language IDs (includes 'markdown') */
export const SUPPORTED_LANGUAGE_IDS: readonly string[] = [
  'markdown',
  ...Array.from(new Set(SUPPORTED_FORMATS.map(f => f.languageId))),
];

/** Default SupportedExtensions object (all enabled, keyed by fileType) */
export function getDefaultSupportedExtensions(): SupportedExtensions {
  const result: SupportedExtensions = {};
  for (const f of SUPPORTED_FORMATS) {
    result[f.fileType] = true;
  }
  return result;
}

/** SupportedExtensions type – keys are fileType values */
export type SupportedExtensions = Record<string, boolean>;
