#!/usr/bin/env node

/**
 * Sync Supported Formats
 *
 * Reads the single source of truth (formats.json) and updates:
 *   1. src/types/formats.ts       – TypeScript format registry (auto-generated)
 *   2. chrome/manifest.json       – content_scripts.matches
 *   3. firefox/manifest.json      – content_scripts.matches
 *   4. package.json               – activationEvents + contributes.languages
 *   5. chrome/src/popup/popup.html – format checkbox list
 *
 * Run:  node scripts/sync-formats.js
 * Also invoked automatically at the start of every platform build.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

// ---------------------------------------------------------------------------
// Read source config
// ---------------------------------------------------------------------------
const config = JSON.parse(
  fs.readFileSync(path.join(projectRoot, 'formats.json'), 'utf8')
);

// ---------------------------------------------------------------------------
// Derive full format definitions from minimal JSON config
// ---------------------------------------------------------------------------

/** 'vega-lite' → 'Vega-Lite', 'mermaid' → 'Mermaid' */
function capitalize(s) {
  return s.replace(/(^|-)(\w)/g, (_, dash, c) => (dash ? '-' : '') + c.toUpperCase());
}

const formats = config.formats.map(f => {
  const languageId = f.languageId || f.fileType;
  return {
    fileType: f.fileType,
    extensions: f.extensions,
    languageId,
    // VS Code language aliases: [Capitalized, lowercase] for each contributing fileType
    aliases: [capitalize(f.fileType), f.fileType],
  };
});

let changed = false;

// ---------------------------------------------------------------------------
// Helper: write file only if content actually changed
// ---------------------------------------------------------------------------
function writeIfChanged(filePath, content) {
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
  if (existing !== content) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`  • Updated ${path.relative(projectRoot, filePath)}`);
    changed = true;
  }
}

// ---------------------------------------------------------------------------
// Helper: update JSON file with a mutator, preserving formatting
// ---------------------------------------------------------------------------
function updateJsonFile(filePath, mutator) {
  const raw = fs.readFileSync(filePath, 'utf8');
  const json = JSON.parse(raw);
  mutator(json);
  const updated = JSON.stringify(json, null, 2) + '\n';
  if (raw !== updated) {
    fs.writeFileSync(filePath, updated, 'utf8');
    console.log(`  • Updated ${path.relative(projectRoot, filePath)}`);
    changed = true;
  }
}

// ---------------------------------------------------------------------------
// 1. Generate src/types/formats.ts
// ---------------------------------------------------------------------------
function generateFormatsTs() {
  const lines = [
    '// AUTO-GENERATED by scripts/sync-formats.js — DO NOT EDIT',
    '// Source of truth: formats.json',
    '',
    '/**',
    ' * Definition of a supported file format',
    ' */',
    'export interface FormatDefinition {',
    '  /** Internal file type identifier, also used as settings key (e.g., \'mermaid\', \'vega-lite\') */',
    '  fileType: string;',
    '  /** File extensions without dot (e.g., [\'mermaid\', \'mmd\']) */',
    '  extensions: string[];',
    '  /** VS Code language ID (e.g., \'mermaid\', \'graphviz\') */',
    '  languageId: string;',
    '}',
    '',
    '/**',
    ' * All supported non-markdown formats.',
    ' * Markdown (.md, .markdown) is always supported and not listed here.',
    ' */',
    `export const SUPPORTED_FORMATS: readonly FormatDefinition[] = ${JSON.stringify(
      formats.map(({ aliases, ...rest }) => rest),
      null,
      2,
    )};`,
    '',
    '// =============================================================================',
    '// Derived lookup tables (built once from SUPPORTED_FORMATS)',
    '// =============================================================================',
    '',
    "/** Map file extension (without dot) → fileType. Includes 'md'/'markdown' → 'markdown'. */",
    "export const EXTENSION_TO_FILE_TYPE: Record<string, string> = { md: 'markdown', markdown: 'markdown' };",
    'for (const f of SUPPORTED_FORMATS) {',
    '  for (const ext of f.extensions) {',
    '    EXTENSION_TO_FILE_TYPE[ext] = f.fileType;',
    '  }',
    '}',
    '',
    "/** Map dotted extension (e.g. '.mermaid') → fileType */",
    'export const DOT_EXTENSION_TO_FILE_TYPE: Record<string, string> = {};',
    'for (const f of SUPPORTED_FORMATS) {',
    '  for (const ext of f.extensions) {',
    '    DOT_EXTENSION_TO_FILE_TYPE[`.${ext}`] = f.fileType;',
    '  }',
    '}',
    '',
    '/** All supported extensions with dot, including markdown */',
    'export const ALL_SUPPORTED_EXTENSIONS: readonly string[] = [',
    "  '.md', '.markdown',",
    "  ...SUPPORTED_FORMATS.flatMap(f => f.extensions.map(e => `.${e}`)),",
    // Sort longest first so compound extensions (e.g. .slide.md) match before shorter ones (.md)
    '].sort((a, b) => b.length - a.length);',
    '',
    '/** All supported extensions without dot, excluding markdown */',
    'export const ALL_FORMAT_EXTENSIONS: readonly string[] =',
    "  SUPPORTED_FORMATS.flatMap(f => f.extensions);",
    '',
    "/** Unique VS Code language IDs (includes 'markdown') */",
    'export const SUPPORTED_LANGUAGE_IDS: readonly string[] = [',
    "  'markdown',",
    '  ...Array.from(new Set(SUPPORTED_FORMATS.map(f => f.languageId))),',
    '];',
    '',
    '/** Default SupportedExtensions object (all enabled, keyed by fileType) */',
    'export function getDefaultSupportedExtensions(): SupportedExtensions {',
    '  const result: SupportedExtensions = {};',
    '  for (const f of SUPPORTED_FORMATS) {',
    '    result[f.fileType] = true;',
    '  }',
    '  return result;',
    '}',
    '',
    '/** SupportedExtensions type – keys are fileType values */',
    'export type SupportedExtensions = Record<string, boolean>;',
    '',
  ];

  writeIfChanged(
    path.join(projectRoot, 'src/types/formats.ts'),
    lines.join('\n'),
  );
}

// ---------------------------------------------------------------------------
// 2 & 3. Update chrome/manifest.json and firefox/manifest.json
// ---------------------------------------------------------------------------
function buildContentScriptMatches() {
  // All extensions including markdown
  const allExts = ['md', 'markdown', ...formats.flatMap(f => f.extensions)];
  const matches = [];
  for (const ext of allExts) {
    matches.push(`file://*/*.${ext}`);
  }
  for (const ext of allExts) {
    matches.push(`*://*/*.${ext}`);
  }
  return matches;
}

function updateManifest(manifestPath) {
  updateJsonFile(manifestPath, (manifest) => {
    // Use wildcard matches for all protocols since content-detector.js handles file type detection
    // file:// for local files, http/https for web
    const matches = ['file:///*', '*://*/*'];
    if (manifest.content_scripts && manifest.content_scripts[0]) {
      manifest.content_scripts[0].matches = matches;
    }
  });
}

// ---------------------------------------------------------------------------
// 4. Update package.json (activationEvents + contributes.languages)
// ---------------------------------------------------------------------------
function updatePackageJson() {
  updateJsonFile(path.join(projectRoot, 'package.json'), (pkg) => {
    // activationEvents: keep onLanguage:markdown and onLanguage:xml, add format languages
    const uniqueLangIds = Array.from(new Set(formats.map(f => f.languageId)));
    pkg.activationEvents = [
      'onLanguage:markdown',
      ...uniqueLangIds.map(id => `onLanguage:${id}`),
      'onLanguage:xml',
    ];

    // contributes.languages: rebuild from formats (shared languageId entries are merged)
    const langMap = new Map();
    for (const fmt of formats) {
      if (!langMap.has(fmt.languageId)) {
        langMap.set(fmt.languageId, {
          id: fmt.languageId,
          aliases: [...fmt.aliases],
          extensions: fmt.extensions.map(e => `.${e}`),
        });
      } else {
        // Merge extensions into existing entry (e.g. vega + vega-lite share languageId 'vega')
        const existing = langMap.get(fmt.languageId);
        for (const ext of fmt.extensions) {
          const dotExt = `.${ext}`;
          if (!existing.extensions.includes(dotExt)) {
            existing.extensions.push(dotExt);
          }
        }
        // Merge aliases
        for (const alias of fmt.aliases) {
          if (!existing.aliases.includes(alias)) {
            existing.aliases.push(alias);
          }
        }
      }
    }

    if (pkg.contributes) {
      pkg.contributes.languages = Array.from(langMap.values());
    }
  });
}

// ---------------------------------------------------------------------------
// 5. Update popup.html format checkboxes
// ---------------------------------------------------------------------------
function updatePopupHtml(popupPath) {
  const html = fs.readFileSync(popupPath, 'utf8');

  // Build new checkbox block
  const checkboxLines = formats.map(f => {
    const checkboxId = `support-${f.fileType}`;
    const i18nKey = `settings_support_${f.fileType.replace(/-/g, '_')}`;
    return '            <label class="checkbox-label">\n' +
      `              <input type="checkbox" id="${checkboxId}">\n` +
      `              <span data-i18n="${i18nKey}"></span>\n` +
      '            </label>';
  });
  const newBlock =
    '          <div class="format-checkboxes">\n' +
    checkboxLines.join('\n') + '\n' +
    '          </div>';

  // Replace existing format-checkboxes div
  const updated = html.replace(
    /          <div class="format-checkboxes">[\s\S]*?          <\/div>/,
    newBlock,
  );

  if (updated !== html) {
    fs.writeFileSync(popupPath, updated, 'utf8');
    console.log(`  • Updated ${path.relative(projectRoot, popupPath)}`);
    changed = true;
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
export default function syncFormats() {
  console.log('📋 Syncing supported formats...');
  changed = false;

  generateFormatsTs();

  updateManifest(path.join(projectRoot, 'chrome/manifest.json'));
  updateManifest(path.join(projectRoot, 'firefox/manifest.json'));

  updatePackageJson();

  updatePopupHtml(path.join(projectRoot, 'chrome/src/popup/popup.html'));

  if (!changed) {
    console.log('  ✓ All format files are up to date');
  }
}

// Run directly
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  syncFormats();
}
